### ISSUE TITLE
Table Kung Fu

### ISSUE THREAD

**Issue by sirinath** [asciidoctor/asciidoctor-leanpub-converter#45]
It is possible to add vertical and horizontal merge, special 1st and last rows and columns, special alternating rows or columns, with the ability to represent the same in Leanpub

**Comment by ysb33r** [comment]
Colspan and rowspan are not supported at present - this is a limitation of Leanpub, not Asciidoctor. Using colspan will result in the initial column being populated, but subsequent being empty. There is no easy solution to this.
