### ISSUE TITLE
Simple Tree Gen

### ISSUE THREAD

**Issue by sirinath** [asciidoctor/asciidoctor-leanpub-converter#46]
I want to add simple tree diagrams to a text. Is possible to add an easy tree generation feature.

E.g.

```
- level 1 (A)
-- child of level A (B)
---  child of B
-- 2nd child of A
- 2nd child of root
```

**Comment by ysb33r** [comment]
That is not supported directly in Asciidoctor (better ask in more detail on the [forum](http://discuss.asciidoctor.org/)). 

However it should be possible to easily do if you also load the [asciidoctor-diagram extension](http://asciidoctor.org/docs/asciidoctor-diagram/). This works with the Leanpub converter. I have already tested it, but not yet pushed the example upstream.

**Comment by sirinath** [comment]
This look like an overkill for simple tree and labeled flow diagrams but until there is an alternative it might do.

**Comment by ysb33r** [comment]
@sirinath Have a look at the [MonoTree](https://github.com/allati/asciidoctor-extension-monotree) extension.
